site_name: Pydantic Settings AWS
site_description: AWS Secrets Manger & Parameter Store for Pydantic Settings
repo_url: https://github.com/ceb10n/pydantic-settings-aws
site_url: https://ceb10n.github.io/pydantic-settings-aws/

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - mkdocstrings
  - search
  - git-committers:
      repository: ceb10n/pydantic-settings-aws
      branch: master

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Pydantic Settings AWS Docs: index.md
  - Examples:
    - Secrets Manager: examples/secrets-manager.md
  - Reference: reference.md

extra_css:
  - stylesheets/extra.css
