site_name: Pydantic Settings AWS

theme:
  name: "material"

nav:
  - Pydantic Settings AWS Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - explanation.md
