site_name: Pydantic Settings AWS

theme:
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Pydantic Settings AWS Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - explanation.md
